default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  host: localhost
  username: iou
  password: iou
  port: 3306
  pool: 20
  reconnect: true

development:
  <<: *default
  database: fusion_dev

test:
  <<: *default
  database: fusion_test

