# frozen_string_literal: true

class AddOffers < ActiveRecord::Migration[5.2]
  def change
    create_table :offers do |t|
      t.integer :user_id
      t.string :title
      t.text :description
      t.datetime :created_on
      t.datetime :updated_on
      t.datetime :start_date
      t.datetime :end_date
      t.decimal :amount
      t.decimal :rate
      t.integer :length_max
      t.decimal :contract_amount
      t.integer :nonpay_status
      t.datetime :nonpay_date
      t.datetime :reserved_at
      t.decimal :requested_amount
      t.integer :topic_id
      t.text :description_html
      t.string :permalink
      t.string :purpose
      t.string :payment_type
      t.decimal :bids_amount
      t.decimal :amount_nsf_unpaid
      t.string :loan_state
      t.string :offer_state
      t.decimal :ratio_di
      t.decimal :suggested_rate
      t.string :cached_state
      t.string :active_state
      t.integer :score_bni
      t.integer :score_vantage
      t.integer :score_iou
      t.text :data
      t.string :late_status
      t.string :writeoff_status
      t.integer :workflow_user
      t.string :workflow_state
      t.string :workflow_stage
      t.datetime :workflow_time
      t.string :accord_state
      t.string :opt_status
      t.integer :workflow_urgency
      t.integer :from_broker_id
      t.datetime :t0date
      t.integer :workflow_importance
      t.datetime :activation_time
      t.string :loan_category
      t.integer :current_lender_id
      t.text :cache
      t.string :from_broker_permalink
      t.integer :workflow_processor_id
      t.integer :workflow_underwriter_id
      t.string :legal_status
      t.datetime :legal_status_date
      t.decimal :cd_loan_amount
      t.integer :cd_loan_term
      t.decimal :cd_loan_rate
      t.datetime :cd_preparation_date
      t.datetime :cd_loan_start_date
      t.decimal :cd_gfee_rate
      t.decimal :cd_closing_fee
      t.decimal :cd_regular_repayment_amount
      t.integer :cd_payment_count
      t.date :cd_pay_date_first
      t.date :cd_pay_date_last
      t.decimal :cd_total_interest
      t.date :cd_interest_start_date
      t.decimal :cd_last_pay_amount
      t.decimal :cd_gfee_payment
      t.decimal :cd_gfee_total
      t.decimal :cd_payment_with_gfee
      t.decimal :cd_ratio_di
      t.decimal :cd_nsf_fee
      t.integer :eligible_for_renewal
      t.integer :eligible_for_renewal_in_days
      t.decimal :uw_amount_net
      t.datetime :estimated_closing_date
      t.datetime :loan_closing_invite
      t.string :state_of_loan
      t.integer :promo_code_id
      t.string :promo_method
      t.string :channel
      t.integer :primary_guarantor_id
      t.integer :allow_accept_funding
      t.date :application_date
      t.datetime :contract_sold_date
      t.datetime :resolved_at
      t.integer :uw_declared_as_renewal
      t.datetime :workflow_underwriter_date
      t.datetime :workflow_processor_date
      t.integer :workflow_renewal_specialist_id
      t.datetime :workflow_renewal_specialist_date
      t.integer :workflow_audited
      t.integer :is_renewed
      t.integer :is_renewal
      t.integer :renew_from_id
      t.integer :country_id
      t.integer :has_lender_deposit_statements
      t.integer :money_mart
      t.integer :iou_score_value
      t.string :iou_score_letter
      t.string :renewal_status
      t.integer :workflow_lead_originator_id
      t.string :renewal_type
      t.string :pmt_frequency
      t.datetime :workflow_lead_originator_date
      t.string :cd_payment_frequency
      t.string :payoff_received_from
      t.integer :payoff_resolved
      t.string :payoff_request_processed
      t.string :payoff_request_type
      t.string :payoff_request_reason
      t.date :payoff_request_on
      t.integer :payoff_request_amount
      t.string :collection_status
      t.integer :sent_investor_referral
      t.integer :investor_referral_id
      t.datetime :sent_investor_referral_on
      t.datetime :investor_reviewed_on
      t.integer :investor_reviewal
      t.integer :auto_change_payment_plan
      t.string :next_payment_plan
      t.datetime :investor_unreferred_on
      t.integer :reage_no
      t.string :lien_position
      t.string :score_tier
      t.integer :management_exception
      t.integer :exception_by
      t.integer :broker_contact_id
      t.integer :eligible_for_renewal_with_balance
      t.integer :workflow_closer_id
      t.datetime :workflow_closer_date
      t.integer :cd_interest_method
      t.integer :is_ecoa_notice_sent
    end
  end
end
